version: '3.8'

services:
  app:
    image: college:latest
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    container_name: go-college
    ports:
      - 8995:8995
    volumes:
      - ./:/go/src
    networks:
      - college

networks:
  college:
    name: college