name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Docker push
        env:
          REPO: golang-college-ec2
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest ${{ secrets.DOCKER_USER }}/$REPO:latest
          docker push ${{ secrets.DOCKER_USER }}/$REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Copy files with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          envs: GITHUB_SHA
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USER }}/golang-college-ec2
            docker stop go-college
            docker rm go-college
            docker run -d --name go-college -p 8995:8995 ${{ secrets.DOCKER_USER }}/golang-college-ec2
 